<?php
$lang = array(
    // General
    "welcome" => "Hoş Geldiniz",
    "logout" => "Çıkış Yap",
    "login" => "Giriş Yap",
    "register" => "Kayıt Ol",
    "admin" => "Yönetici",
    "employee" => "Çalışan",
    "IK" => "İK",
    "update" => "Güncelle",
    "sign_in" => "Giriş Yap",
    "sign_up" => "Kayıt Ol",
    "remember_me" => "Beni Hatırla",
    "reset_pass" => "Şifreyi Sıfırla",
    "reset_pass_form" => "Şifre Sıfırlama Formu",
    "have_account" => "Hesabınız yok mu?",
    "phone_number" => "Telefon Numarası",
    "role" => "Rol",
    "select_role" => "Rol Seçin",
    "update_contact" => "İletişim Bilgilerini Güncelle",
    "google_maps_embed" => "Google Maps Gömülü Kodu",
    "facebook_link" => "Facebook Linki",
    "twitter_link" => "Twitter Linki",
    "linkedin_link" => "LinkedIn Linki",
    "app_date" => "Başvuru Tarihi",
    "read"=> "Okundu",
    "read_status" => "Okuma Durumu",
    "view_resume" => "Özgeçmişi Görüntüle",
    "mark_as_read" => "Okundu Olarak İşaretle",
    "user_list" => "Kullanıcı Listesi",
    "create_at" => "Oluşturulma Tarihi",
    
    // Header
    "home" => "Ana Sayfa",
    "about" => "Hakkımızda",
    "contact" => "İletişim",
    "blog_list" => "Blog Listesi",
    // User Profile
    "user_profile" => "Kullanıcı Profili",
    "profile" => "Profil",
    "edit_profile" => "Profili Düzenle",
    "username" => "Kullanıcı Adı",
    "email" => "E-posta Adresi",
    "password" => "Şifre",
    "save_changes" => "Değişiklikleri Kaydet",
    "cancel" => "İptal",
    // Jobs
    "create_job" => "İş Oluştur",
    "job_applications" => "İş Başvuruları",
    "job_id" => "İş Id",
    "company_name" => "Şirket Adı",
    "job_list" => "İş Listesi",
    "title" => "Başlık",
    "description" => "Açıklama",
    "sector" => "Sektör",
    "city" => "Şehir",
    "create_job" => "İş Oluştur",
    "actions" => "İşlemler",
    "edit" => "Düzenle",
    "edit_job" => "İşi Düzenle",
    "delete" => "Sil",
    "cover_letter" => "Ön Yazı",
    "resume" => "Özgeçmiş",
    // Blog
    "blogs" => "Bloglar",
    "add_blog" => "Blog Ekle",
    "blog_id" => "Blog Id",
    "content" => "İçerik",
    "no_blogs" => "Henüz blog yok.",
    "blog_title" => "Blog Başlığı",
    "blog_content" => "Blog İçeriği",
    "author" => "Yazar",
    "actions" => "İşlemler",
    "create_blog" => "Blog Oluştur",
    "edit_blog" => "Blog Düzenle",
    "delete_blog" => "Blog Sil",
    
    // Comments
    "comments" => "Yorumlar",
    "comment" => "Yorum",
    "name" => "Ad",
    "add_comment" => "Yorum Ekle",
    "subject" => "Konu",
    "no_comments" => "Henüz yorum yok.",
    "comment_placeholder" => "Yorumunuzu buraya yazın...",
    "submit" => "Gönder",
    // Notifications
    "success" => "Başarılı",
    "error" => "Hata",
    "info" => "Bilgi",
    "warning" => "Uyarı",
    // Footer
    "footer_text" => "© 2024 Yusuf Atakan Özmen. Tüm Hakları Saklıdır.",
    // Other
    "language" => "Dil",
    "english" => "İngilizce",
    "turkish" => "Türkçe",
    "select_language" => "Dil Seçin",
    // Dashboard
    "dashboard" => "Gösterge Paneli",
    "total_applications" => "Toplam Başvurular",
    "total_blogs" => "Toplam Bloglar",
    "total_comments" => "Toplam Yorumlar",
    "total_messages" => "Toplam Mesajlar",

    // Change Password
    "password" => "Şifre",
    "change_password" => "Şifre Değiştir",
    "new_password" => "Yeni Şifre",
    "confirm_password" => "Şifreyi Onayla",
    // About
    "create_about" => "Hakkımızda Oluştur",
    "about" => "Hakkımızda",
    "text" => "Metin :",
    "image" => "Resim :",
    "edit_about" => "Hakkımızda Düzenle",
    "new_image" => "Yeni Resim",

    // Team
    "team" => "Takım",
    "create_team" => "Takım Oluştur",
    "edit_team" => "Takım Düzenle",
    "team_list" => "Takım Listesi",
    "position" => "Pozisyon",
    "social_media" => "Sosyal Medya",
    "add_team" => "Takım Ekle",

    //sidebar
    "dashboard" => "Gösterge Paneli",
    "main_navigation" => "Ana Menü",
    "jobs" => "İşler",
);
?>