<?php
$lang = array(
    // General
    "welcome" => "Welcome",
    "logout" => "Logout",
    "login" => "Login",
    "register" => "Register",
    "admin" => "Admin",
    "employee" => "Employee",
    "IK" => "HR",
    "update" => "Update",
    "sign_in" => "Sign In",
    "sign_up" => "Sign Up Here",
    "remember_me" => "Remember Me",
    "reset_pass" => "Reset Password",
    "reset_pass_form" => "Reset Password Form",
    "have_account" => "Don't have an account?",
    "phone_number" => "Phone Number",
    "role" => "Role",
    "select_role" => "Select Role",
    "update_contact" => "Update Contact Information",
    "google_maps_embed" => "Google Maps Embed Code",
    "facebook_link" => "Facebook Link",
    "twitter_link" => "Twitter Link",
    "linkedin_link" => "LinkedIn Link",
    "app_date" => "Application Date",
    "read_status" => "Read Status",
    "view_resume" => "View Resume",
    "mark_as_read" => "Mark as Read",
    "read" => "Read",
    // Header
    "home" => "Home",
    "about" => "About",
    "contact" => "Contact",
    "blog_list" => "Blog List",
    // User Profile
    "user_profile" => "User Profile",
    "profile" => "Profile",
    "edit_profile" => "Edit Profile",
    "username" => "Username",
    "email" => "Email",
    "password" => "Password",
    "save_changes" => "Save Changes",
    "cancel" => "Cancel",
    // Jobs
    "create_job" => "Create Job",
    "job_applications" => "Job Applications",
    "job_id" => "Job Id",
    "company_name" => "Company Name",
    "job_list" => "Job List",
    "title" => "Title",
    "description" => "Description",
    "sector" => "Sector",
    "city" => "City",
    "create_job" => "Create Job",
    "actions" => "Actions",
    "edit_job" => "Edit Job",
    "edit" => "Edit",
    "delete" => "Delete",
    "cover_letter" => "Cover Letter",
    "resume" => "Resume",
    "user_list" => "User List",
    "create_at" => "Create At",
    

    // Blog
    "blogs" => "Blogs",
    "add_blog" => "Add Blog",
    "content" => "Content",
    "no_blogs" => "No blogs yet.",
    "blog_id" => "Blog Id",
    "blog_title" => "Blog Title",
    "blog_content" => "Blog Content",
    "author" => "Author",
    "actions" => "Actions",
    "create_blog" => "Create Blog",
    "edit_blog" => "Edit Blog",
    "delete_blog" => "Delete Blog",
    
    // Comments
    "comments" => "Comments List",
    "comment" => "Comment",
    "name" => "Name",
    "subject" => "Subject",
    "add_comment" => "Add Comment",
    "no_comments" => "No comments yet.",
    "comment_placeholder" => "Write your comment here...",
    "submit" => "Submit",
    // Notifications
    "success" => "Success",
    "error" => "Error",
    "info" => "Info",
    "warning" => "Warning",
    // Footer
    "footer_text" => "© 2024 Yusuf Atakan Özmen. All Rights Reserved.",
    // Other
    "language" => "Language",
    "english" => "English",
    "turkish" => "Turkish",
    "select_language" => "Select Language",
    // Dashboard
    "dashboard" => "Dashboard",
    "total_applications" => "Total Applications",
    "total_blogs" => "Total Blogs",
    "total_comments" => "Total Comments",
    "total_messages" => "Total Messages",

    // Change Password
    "password" => "Password",
    "change_password" => "Change Password",
    "new_password" => "New Password",
    "confirm_password" => "Confirm Password",

    // About
    "create_about" => "Create About",
    "about" => "About",
    "text" => "Text :",
    "image" => "Image",
    "edit_about" => "Edit About",
    "new_image" => "New Image",
    
    // Team
    "team" => "Team",
    "create_team" => "Create Team",
    "edit_team" => "Edit Team",
    "team_list" => "Team List",
    "position" => "Position",
    "social_media" => "Social Media",
    "add_team" => "Add Team Member",

    //sidebar
    "dashboard" => "Dashboard",
    "main_navigation" => "Main Navigation",
    "jobs" => "Jobs",
);
?>